#pragma once

// Enable `QK_MAKE`
#define ENABLE_COMPILE_KEYCODE

// Handedness
#define EE_HANDS

// Compose
#define COMPOSE_KEY KC_APP

// Course
#define COURSE_CANCEL_KEY KC_ESC
#define COURSE_TAPPING_TERM 500

// Layers
#define LAYER_STATE_16BIT

// Tapping
#define TAPPING_TOGGLE 2
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM TAPPING_TERM
#define QUICK_TAP_TERM_PER_KEY

// One Shot
#define ONESHOT_TAP_TOGGLE TAPPING_TOGGLE
#define ONESHOT_TIMEOUT 0

// Dynamic Macro
#define DYNAMIC_MACRO_NO_NESTING
#define DYNAMIC_MACRO_DELAY 33

// Unicode
#define UNICODE_CYCLE_PERSIST false
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_WINCOMPOSE, UNICODE_MODE_WINDOWS
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))
#define UNICODE_KEY_WINC COMPOSE_KEY

// Caps Word
#define CAPS_WORD_IDLE_TIMEOUT 0

// Combos
#define COMBO_TERM 50
#define COMBO_STRICT_TIMER
#define COMBO_MUST_TAP_PER_COMBO

// Mouse
#define MK_COMBINED
#define MOUSEKEY_INTERVAL 24
#define MOUSEKEY_WHEEL_INTERVAL 80
#define MK_C_OFFSET_0 1
#define MK_C_OFFSET_1 1
#define MK_C_OFFSET_2 2
#define MK_C_INTERVAL_0 32
#define MK_C_INTERVAL_1 24
#define MK_C_INTERVAL_2 16
#define MK_W_OFFSET_0 1
#define MK_W_OFFSET_1 1
#define MK_W_OFFSET_2 1
#define MK_W_INTERVAL_0 800
#define MK_W_INTERVAL_1 200
#define MK_W_INTERVAL_2 50
